- SANS Institute - Security Awareness Maturity Model - https://www.sans.org/security-resources/posters/security-awareness-roadmap-managing-human-risk/385/download 
- SANS Institute - Security Awareness Resources - https://www.sans.org/security-awareness-training/ 
- Fogg Behavior Model - https://behaviormodel.org
- O'Reilly - Designing Culture - https://www.oreilly.com/content/designing-culture/ 
- Can Security Awareness Training Change Behavior and Reduce Risk? - https://www.govtech.com/security/can-security-awareness-training-change-behavior-and-reduce-risk.html 
- People power: making your people an essential part of your cyber security strategy - https://www.paconsulting.com/insights/why-a-human-side-is-essential-to-effective-cyber-security/ 
- How can you improve cyber security awareness in your organisation? - https://www.paconsulting.com/insights/how-can-you-improve-cyber-security-awareness-in-your-organisation/ 
- The Human Side of Cybersecurity - https://www.infosecurity-magazine.com/blogs/the-human-side-of-cybersecurity/ 
- Individual Differences in Cyber Security Behaviors: An Examination of Who Is Sharing Passwords - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4291202/ 
- Global Cyber Security Capacity Centre: Draft Working Paper Cyber Security Awareness Campaigns - Why do they fail to change behaviour? - https://discovery.ucl.ac.uk/id/eprint/1468954/1/Awareness%20CampaignsDraftWorkingPaper.pdf 
- Centre for the Protection of National Infrastructure - Embedding Security Behaviour Change - https://www.cpni.gov.uk/embedding-security-behaviour-change 
- Centre for the Protection of National Infrastructure - Catch the Phish - Quiz Example - https://www.cpni.gov.uk/system/files/documents/29/97/quiz.pdf 
- Information Security Awareness Campaign Materials - British Columbia - https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/information-security/information-security-awareness 
- Share Aware resources for schools and teachers - https://learning.nspcc.org.uk/research-resources/schools/share-aware-teaching
- Online safety - https://www.nspcc.org.uk/keeping-children-safe/online-safety/#esafety
- Playing Minecraft safely - https://www.nspcc.org.uk/globalassets/documents/online-safety/minecraft-pdf.pdf
- Guide to apps, games and social media sites - https://www.net-aware.org.uk
- Helping parents keep their children safe online - https://www.internetmatters.org
- Posters, stickers and postcards to help you promote good data protection practice - https://ico.org.uk/for-organisations/posters-stickers-and-e-learning/
- Europol - YOUR LIFE IS ONLINE. PROTECT IT! - https://www.europol.europa.eu/activities-services/public-awareness-and-prevention-guides/your-life-online-protect-it
- CIS - Daily Tips - https://www.cisecurity.org/resources/?type=daily-tip
- SANS - Security Awareness Tip of The Day - https://www.sans.org/tip-of-the-day 
- FTC - Videos to help you be #CyberAware - https://www.consumer.ftc.gov/blog/2016/09/3-videos-help-you-be-cyberaware 
- Please don't send me to cybersecurity training - https://www.csoonline.com/article/3225471/please-dont-send-me-to-cybersecurity-training.html 
- SANS Reading Room - Online Safety in a Foreign Language - Connecting with Teens - https://www.sans.org/reading-room/whitepapers/awareness/online-safety-foreign-language-connecting-teens-38080 
- Top Three Online Threats: What Can Harm Our Kids? - https://www.rsaconference.com/library/video/cybersmart-parents-education-workshop-lance-spitzner  
- Take Five - To Stop Fraud - https://takefive-stopfraud.org.uk 
- Cybersecurity in the workplace is everyone’s business - https://staysafeonline.org/wp-content/uploads/2017/10/Cybersecurity-in-the-workplace-is-everyones-business-infographic.pdf  
- 131 Cybersecurity Tips that Anyone Can Apply - https://heimdalsecurity.com/blog/cyber-security-tips/  
- E-safety classroom materials - https://www.kelsi.org.uk/child-protection-and-safeguarding/e-safety/e-safety-classroom-materials
- Childnet International - Smartie the Penguin - https://www.childnet.com/resources/smartie-the-penguin
- NSPCC - Online Safety - https://www.nspcc.org.uk/keeping-children-safe/online-safety/
- GetCyberSafe Canada - https://www.getcybersafe.gc.ca/en
